version: 2
updates:
  - package-ecosystem: "npm"
    directories:
      - "/"
      - "/packages/client"
      - "/packages/contracts"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "hardhat"
